"""
Seed script: wipes and repopulates the database with realistic demo
data using Faker.

Run manually (`python seed.py`) -- NEVER wired into run.py, since you
don't want demo data appearing every time the dev server starts. This
script DROPS AND RECREATES every table, so anything in the database
before running it is gone, including anything you added by hand
through Postman since the last seed. That's a deliberate tradeoff: the
password scheme below only stays valid if ids are predictable, and
ids are only predictable starting from a clean slate.

Password scheme (for local demo/testing ONLY -- never do this in a
real deployment): every seeded customer's password is
"customerpassword<id>", and every seeded regular mechanic's password
is "mechanicpassword<id>", where <id> is that record's actual
database id. Look up an id in MySQL Workbench and you already know
its password. The one exception is the manager account, whose email
and password come from MANAGER_EMAIL / MANAGER_PASSWORD in .env
instead -- since that's the account you're most likely to log in as
by hand while testing, it gets credentials you actually chose.

Ids after a fresh run:
  Mechanics:
    id 1      -- the manager (credentials from .env)
    ids 2-5   -- four core mechanics, deliberately uneven ticket loads
                 (one busy, one moderate, one light, one with zero
                 tickets -- a realistic "just hired" case)
    ids 6-8   -- three EXTRA mechanics, never assigned to any ticket
                 -- safe to DELETE via the API without touching
                 anything else, specifically for testing
                 delete_mechanic by hand
  Customers:
    ids 1-12  -- core customers, each with at least one ticket
    ids 13-14 -- two EXTRA customers with no tickets -- safe to
                 DELETE via the API for the same reason
  Service tickets:
    ids 1-33  -- spread across all five statuses, each linked to one
                 of customers 1-12 and zero or more of mechanics 2-5
                 only (the extra mechanics 6-8 are never assigned, so
                 deleting them never orphans a ticket)
"""

import os
import random
from decimal import Decimal

from dotenv import load_dotenv
from faker import Faker
from werkzeug.security import generate_password_hash

from app import create_app
from app.extensions import db
from app.models.customer import Customer
from app.models.mechanic import Mechanic
from app.models.service_ticket import ServiceTicket
from config import DevelopmentConfig

load_dotenv()

fake = Faker()

STATUSES = ["Pending", "In Progress", "Completed", "Paid", "Picked Up"]

# Characters a real VIN may contain per ISO 3779 -- excludes I, O, Q,
# matching the Regexp validator in
# app/blueprints/service_ticket/schemas.py. Faker has no built-in VIN
# provider, so this is generated by hand instead.
VIN_CHARS = "ABCDEFGHJKLMNPRSTUVWXYZ0123456789"


def make_vin():
    """Generate a random 17-character string in the same format
    ServiceTicketSchema validates against."""
    return "".join(random.choices(VIN_CHARS, k=17))


def money(low, high):
    """A random Decimal in [low, high], rounded to 2 places -- used
    for salary and cost, both Numeric(10, 2) columns. Built from a
    string rather than a float directly, since float arithmetic can
    introduce the same rounding error Numeric/Decimal exists to avoid.
    """
    return Decimal(f"{random.uniform(low, high):.2f}")


def seed():
    """Wipe every table and repopulate it with demo data."""
    app = create_app(DevelopmentConfig)

    with app.app_context():
        manager_email = os.getenv("MANAGER_EMAIL")
        manager_password = os.getenv("MANAGER_PASSWORD")
        if not manager_email or not manager_password:
            raise RuntimeError(
                "MANAGER_EMAIL and MANAGER_PASSWORD must be set in .env "
                "before seeding -- see README for details."
            )

        print("Dropping and recreating all tables...")
        db.drop_all()
        db.create_all()

        print("Creating manager account...")
        manager = Mechanic(
            name="Morgan Lee",
            email=manager_email,
            phone=fake.phone_number()[:20],
            salary=money(80000, 95000),
            password_hash=generate_password_hash(manager_password),
            role="manager",
        )
        db.session.add(manager)
        db.session.commit()  # id 1

        print("Creating 4 core mechanics...")
        core_mechanics = []
        for _ in range(4):
            mech = Mechanic(
                name=fake.name(),
                email=fake.unique.email(),
                phone=fake.phone_number()[:20],
                salary=money(45000, 70000),
                password_hash=generate_password_hash("placeholder"),
                role="mechanic",
            )
            db.session.add(mech)
            core_mechanics.append(mech)
        db.session.commit()  # ids 2-5

        # Ids only exist after the commit above, so the real
        # id-based password can only be set now.
        for mech in core_mechanics:
            mech.password_hash = generate_password_hash(f"mechanicpassword{mech.id}")
        db.session.commit()

        print("Creating 3 extra mechanics (safe to delete)...")
        extra_mechanics = []
        for _ in range(3):
            mech = Mechanic(
                name=fake.name(),
                email=fake.unique.email(),
                phone=fake.phone_number()[:20],
                salary=money(45000, 70000),
                password_hash=generate_password_hash("placeholder"),
                role="mechanic",
            )
            db.session.add(mech)
            extra_mechanics.append(mech)
        db.session.commit()  # ids 6-8

        for mech in extra_mechanics:
            mech.password_hash = generate_password_hash(f"mechanicpassword{mech.id}")
        db.session.commit()

        print("Creating 12 core customers...")
        core_customers = []
        for _ in range(12):
            cust = Customer(
                name=fake.name(),
                email=fake.unique.email(),
                phone=fake.phone_number()[:20],
                password_hash=generate_password_hash("placeholder"),
            )
            db.session.add(cust)
            core_customers.append(cust)
        db.session.commit()  # ids 1-12

        for cust in core_customers:
            cust.password_hash = generate_password_hash(f"customerpassword{cust.id}")
        db.session.commit()

        print("Creating 2 extra customers (safe to delete)...")
        extra_customers = []
        for _ in range(2):
            cust = Customer(
                name=fake.name(),
                email=fake.unique.email(),
                phone=fake.phone_number()[:20],
                password_hash=generate_password_hash("placeholder"),
            )
            db.session.add(cust)
            extra_customers.append(cust)
        db.session.commit()  # ids 13-14

        for cust in extra_customers:
            cust.password_hash = generate_password_hash(f"customerpassword{cust.id}")
        db.session.commit()

        print("Creating 33 service tickets...")
        # Deliberately uneven workload across the 4 core mechanics:
        # index 0 is assigned to most tickets, index 3 to none.
        assignment_odds = [0.6, 0.35, 0.15, 0.0]

        for i in range(33):
            customer = random.choice(core_customers)
            status = STATUSES[i % len(STATUSES)]  # guarantees every status appears
            service_date = fake.date_between(start_date="-90d", end_date="today")

            ticket = ServiceTicket(
                customer=customer,
                vin=make_vin(),
                service_date=service_date,
                service_desc=fake.sentence(nb_words=8),
                status=status,
                cost=money(75, 1500),
            )
            db.session.add(ticket)
            db.session.flush()  # assigns ticket.id without a full commit

            for mech, odds in zip(core_mechanics, assignment_odds):
                if random.random() < odds:
                    ticket.mechanics.append(mech)

        db.session.commit()  # ids 1-33

        print("\nSeed complete:")
        print(f"  {1 + len(core_mechanics) + len(extra_mechanics)} mechanics "
              f"(1 manager, {len(core_mechanics)} core, "
              f"{len(extra_mechanics)} extra/deletable)")
        print(f"  {len(core_customers) + len(extra_customers)} customers "
              f"({len(core_customers)} core, {len(extra_customers)} extra/deletable)")
        print("  33 service tickets across all 5 statuses")
        print(f"\nManager login: {manager_email} / (see .env)")


if __name__ == "__main__":
    seed()
