"""
Seed script: wipes and repopulates the database with realistic demo
data using Faker.

Run manually (`python seed.py`) -- NEVER wired into run.py, since you
don't want demo data appearing every time the dev server starts. This
script DROPS AND RECREATES every table, so anything in the database
before running it is gone, including anything you added by hand
through Postman since the last seed. That's a deliberate tradeoff: the
password scheme below only stays valid if ids are predictable, and
ids are only predictable starting from a clean slate.

Password scheme (for local demo/testing ONLY -- never do this in a
real deployment): every seeded customer's password is
"customerpassword<id>", and every seeded regular mechanic's password
is "mechanicpassword<id>", where <id> is that record's actual
database id. Look up an id in MySQL Workbench and you already know
its password. The one exception is the manager account, whose email
and password come from MANAGER_EMAIL / MANAGER_PASSWORD in .env
instead -- since that's the account you're most likely to log in as
by hand while testing, it gets credentials you actually chose.

Emails are built from each generated name (see make_email) rather
than Faker's independent fake.email(), so a row's email is always
recognizably tied to the name next to it in MySQL Workbench --
Faker's own email generator has no relationship to the name on the
same record at all. Phone numbers use a fixed pattern (see
make_phone) rather than fake.phone_number(), which sometimes appends
an extension or uses inconsistent international formatting.

"Extra" / "deletable" records exist purely so there's always something
safe to DELETE for manual testing or video demos, without disturbing
any of the core relationships. An extra mechanic is never assigned to
a ticket; an extra customer is never given a ticket (customers WITH a
ticket can no longer be deleted at all, only closed accounts with no
history can); an extra inventory part is never attached to a ticket
(a part that's been used is refused with 409, by design). Re-running
this script always restores the full supply of deletable records.

Ids after a fresh run:
  Mechanics:
    id 1       -- the manager (credentials from .env)
    ids 2-5    -- four core mechanics, deliberately uneven ticket loads
                  (one busy, one moderate, one light, one with zero
                  tickets -- a realistic "just hired" case)
    ids 6-11   -- six EXTRA mechanics, never assigned to any ticket --
                  safe to DELETE via the API, specifically for testing
                  delete_mechanic (or re-testing it across several
                  video takes without running out)
  Customers:
    ids 1-12   -- core customers, each with at least one ticket (and
                  therefore can never be deleted, only updated)
    ids 13-18  -- six EXTRA customers with no tickets -- safe to
                  DELETE via the API, same reasoning as extra mechanics
  Inventory:
    ids 1-10   -- core parts, several attached to existing tickets.
                  Brake Rotor (id 5) is deliberately seeded with only
                  3 in stock, so add-part's over-allocation check
                  (requesting more than what's on hand) has a real,
                  ready-made example to demo without any manual setup.
    ids 11-16  -- six EXTRA parts, never attached to any ticket --
                  safe to DELETE via the API
  Service tickets:
    ids 1-33   -- spread across all five statuses, each linked to one
                  of customers 1-12 and zero or more of mechanics 2-5
                  only (the extra mechanics are never assigned, so
                  deleting them never orphans a ticket). Several also
                  have one or more parts attached from the core
                  inventory catalog, which decrements that part's
                  quantity_on_hand accordingly.
"""

import os
import random
from decimal import Decimal

from dotenv import load_dotenv
from faker import Faker
from werkzeug.security import generate_password_hash

from app import create_app
from app.extensions import db
from app.models.customer import Customer
from app.models.inventory import Inventory
from app.models.mechanic import Mechanic
from app.models.service_ticket import ServiceTicket
from app.models.ticket_part import TicketPart
from config import DevelopmentConfig

load_dotenv()

fake = Faker()

STATUSES = ["Pending", "In Progress", "Completed", "Paid", "Picked Up"]

# Characters a real VIN may contain per ISO 3779 -- excludes I, O, Q,
# matching the Regexp validator in
# app/blueprints/service_ticket/schemas.py. Faker has no built-in VIN
# provider, so this is generated by hand instead.
VIN_CHARS = "ABCDEFGHJKLMNPRSTUVWXYZ0123456789"

# A believable parts catalog -- real part names, a realistic price
# range, and a starting stock count, rather than Faker-generated
# gibberish, since a mechanic reading these on a ticket should
# recognize them at a glance. Brake Rotor is deliberately low-stock
# (see module docstring) so the over-allocation check in add_part_to_ticket
# has a ready-made example.
PARTS_CATALOG = [
    ("Oil Filter", Decimal("12.50"), 40),
    ("Synthetic Oil (5qt)", Decimal("34.99"), 25),
    ("Front Brake Pads (set)", Decimal("58.00"), 15),
    ("Rear Brake Pads (set)", Decimal("52.00"), 15),
    ("Brake Rotor", Decimal("74.50"), 3),
    ("Air Filter", Decimal("18.25"), 30),
    ("Cabin Air Filter", Decimal("21.00"), 30),
    ("Spark Plug", Decimal("8.75"), 60),
    ("Serpentine Belt", Decimal("29.99"), 20),
    ("Wiper Blade (pair)", Decimal("24.50"), 25),
]

EXTRA_PART_NAMES = [
    "Battery Terminal",
    "Coolant Hose",
    "Fuel Filter",
    "Headlight Bulb",
    "Radiator Cap",
    "Timing Belt",
]

_used_emails = set()


def make_vin():
    """Generate a random 17-character string in the same format
    ServiceTicketSchema validates against."""
    return "".join(random.choices(VIN_CHARS, k=17))


def make_name():
    """A generated name, guaranteed not to repeat within this seed
    run -- names feed directly into make_email(), so two people with
    the same name would otherwise collide on the same email."""
    return fake.unique.name()


def make_email(name):
    """Build a predictable, readable email from a generated name,
    rather than Faker's independent fake.email() -- which has no
    relationship to the name on the same row and made seeded records
    confusing to eyeball in MySQL Workbench. Falls back to appending
    a number on the rare chance two names still slugify to the same
    string (e.g. "Jo Ann Lee" and "Joann Lee").
    """
    slug = name.lower().replace(" ", ".").replace("'", "").replace(",", "")
    email = f"{slug}@example.com"
    suffix = 2
    while email in _used_emails:
        email = f"{slug}{suffix}@example.com"
        suffix += 1
    _used_emails.add(email)
    return email


def make_phone():
    """A clean, extension-free US-style phone number. fake.phone_number()
    sometimes appends an extension (x1234) or uses inconsistent
    international formatting -- numerify() with an explicit pattern
    avoids both.
    """
    return fake.numerify("555-###-####")


def money(low, high):
    """A random Decimal in [low, high], rounded to 2 places -- used
    for salary and cost, both Numeric(10, 2) columns. Built from a
    string rather than a float directly, since float arithmetic can
    introduce the same rounding error Numeric/Decimal exists to avoid.
    """
    return Decimal(f"{random.uniform(low, high):.2f}")


def seed():
    """Wipe every table and repopulate it with demo data."""
    app = create_app(DevelopmentConfig)

    with app.app_context():
        manager_email = os.getenv("MANAGER_EMAIL")
        manager_password = os.getenv("MANAGER_PASSWORD")
        if not manager_email or not manager_password:
            raise RuntimeError(
                "MANAGER_EMAIL and MANAGER_PASSWORD must be set in .env "
                "before seeding -- see README for details."
            )

        print("Dropping and recreating all tables...")
        db.drop_all()
        db.create_all()
        _used_emails.clear()
        _used_emails.add(manager_email.lower())

        print("Creating manager account...")
        manager = Mechanic(
            name="Morgan Lee",
            email=manager_email,
            phone=make_phone(),
            salary=money(80000, 95000),
            password_hash=generate_password_hash(manager_password),
            role="manager",
        )
        db.session.add(manager)
        db.session.commit()  # id 1

        print("Creating 4 core mechanics...")
        core_mechanics = []
        for _ in range(4):
            name = make_name()
            mech = Mechanic(
                name=name,
                email=make_email(name),
                phone=make_phone(),
                salary=money(45000, 70000),
                password_hash=generate_password_hash("placeholder"),
                role="mechanic",
            )
            db.session.add(mech)
            core_mechanics.append(mech)
        db.session.commit()  # ids 2-5

        # Ids only exist after the commit above, so the real
        # id-based password can only be set now.
        for mech in core_mechanics:
            mech.password_hash = generate_password_hash(f"mechanicpassword{mech.id}")
        db.session.commit()

        print("Creating 6 extra mechanics (safe to delete)...")
        extra_mechanics = []
        for _ in range(6):
            name = make_name()
            mech = Mechanic(
                name=name,
                email=make_email(name),
                phone=make_phone(),
                salary=money(45000, 70000),
                password_hash=generate_password_hash("placeholder"),
                role="mechanic",
            )
            db.session.add(mech)
            extra_mechanics.append(mech)
        db.session.commit()  # ids 6-11

        for mech in extra_mechanics:
            mech.password_hash = generate_password_hash(f"mechanicpassword{mech.id}")
        db.session.commit()

        print("Creating 12 core customers...")
        core_customers = []
        for _ in range(12):
            name = make_name()
            cust = Customer(
                name=name,
                email=make_email(name),
                phone=make_phone(),
                password_hash=generate_password_hash("placeholder"),
            )
            db.session.add(cust)
            core_customers.append(cust)
        db.session.commit()  # ids 1-12

        for cust in core_customers:
            cust.password_hash = generate_password_hash(f"customerpassword{cust.id}")
        db.session.commit()

        print("Creating 6 extra customers (safe to delete)...")
        extra_customers = []
        for _ in range(6):
            name = make_name()
            cust = Customer(
                name=name,
                email=make_email(name),
                phone=make_phone(),
                password_hash=generate_password_hash("placeholder"),
            )
            db.session.add(cust)
            extra_customers.append(cust)
        db.session.commit()  # ids 13-18

        for cust in extra_customers:
            cust.password_hash = generate_password_hash(f"customerpassword{cust.id}")
        db.session.commit()

        print("Creating 10 core inventory parts...")
        core_parts = []
        for name, price, quantity_on_hand in PARTS_CATALOG:
            part = Inventory(name=name, price=price, quantity_on_hand=quantity_on_hand)
            db.session.add(part)
            core_parts.append(part)
        db.session.commit()  # ids 1-10

        print("Creating 6 extra inventory parts (safe to delete)...")
        for name in EXTRA_PART_NAMES:
            db.session.add(
                Inventory(
                    name=name, price=money(5, 60), quantity_on_hand=random.randint(10, 40)
                )
            )
        db.session.commit()  # ids 11-16

        print("Creating 33 service tickets...")
        # Deliberately uneven workload across the 4 core mechanics:
        # index 0 is assigned to most tickets, index 3 to none.
        assignment_odds = [0.6, 0.35, 0.15, 0.0]

        for i in range(33):
            customer = random.choice(core_customers)
            status = STATUSES[i % len(STATUSES)]  # guarantees every status appears
            service_date = fake.date_between(start_date="-90d", end_date="today")

            ticket = ServiceTicket(
                customer=customer,
                vin=make_vin(),
                service_date=service_date,
                service_desc=fake.sentence(nb_words=8),
                status=status,
                cost=money(75, 1500),
            )
            db.session.add(ticket)
            db.session.flush()  # assigns ticket.id without a full commit

            for mech, odds in zip(core_mechanics, assignment_odds):
                if random.random() < odds:
                    ticket.mechanics.append(mech)

            # Roughly 2 in 3 tickets get 1-3 parts attached, at their
            # current catalog price, and that quantity is deducted
            # from the part's stock -- gives add-part, the parts list
            # on a ticket, the "used part can't be deleted" 409, and
            # realistic post-seed stock levels something real to show.
            if random.random() < 0.65:
                for part in random.sample(core_parts, k=random.randint(1, 3)):
                    qty = min(random.randint(1, 2), part.quantity_on_hand)
                    if qty == 0:
                        continue  # this part is already out of stock in this seed run
                    db.session.add(
                        TicketPart(
                            ticket=ticket,
                            part=part,
                            quantity=qty,
                            unit_price=part.price,
                        )
                    )
                    part.quantity_on_hand -= qty

        db.session.commit()  # ids 1-33

        print("\nSeed complete:")
        print(f"  {1 + len(core_mechanics) + len(extra_mechanics)} mechanics "
              f"(1 manager, {len(core_mechanics)} core, "
              f"{len(extra_mechanics)} extra/deletable)")
        print(f"  {len(core_customers) + len(extra_customers)} customers "
              f"({len(core_customers)} core, {len(extra_customers)} extra/deletable)")
        print(f"  {len(PARTS_CATALOG) + len(EXTRA_PART_NAMES)} inventory parts "
              f"({len(PARTS_CATALOG)} core, {len(EXTRA_PART_NAMES)} extra/deletable)")
        print("  33 service tickets across all 5 statuses, most with parts attached")
        print(f"\nManager login: {manager_email} / (see .env)")


if __name__ == "__main__":
    seed()
